-- Migration: 0004_update_template_fields
-- Description: Update template input fields per user feedback

-- ─── t-app-01: Application Services 設定ガイド ───
UPDATE templates SET input_fields_json = '{"fields":[{"id":"service_name","label":"扱う Cloudflare サービス","type":"text","required":true,"placeholder":"例: WAF, CDN, Load Balancing"},{"id":"use_case","label":"目的・ユースケース","type":"textarea","required":true,"placeholder":"何を実現するか（例: WordPress を WAF で保護する）"},{"id":"services_used","label":"使用する Cloudflare サービス","type":"tag_select","required":true,"options":["WAF","CDN","Bot Management","Load Balancing","Rules (Cache / Page / Transform)","SSL/TLS","Waiting Room","Log Push","Log Explorer","Spectrum","Version Management","API Protection","Page Shield","Argo Smart Routing"]},{"id":"previous_solution","label":"Cloudflare 採用前のソリューション","type":"textarea","required":false,"placeholder":"例: Akamai CDN + Imperva WAF を利用していた。課題は..."},{"id":"target_audience","label":"対象読者","type":"tag_select","required":true,"options":["インフラエンジニア","セキュリティエンジニア","SRE","Web 開発者","IT 管理者","ネットワークエンジニア"]},{"id":"target_audience_other","label":"対象読者（その他）","type":"text","required":false,"placeholder":"上記にない場合は自由記述"},{"id":"steps","label":"設定手順（箇条書き）","type":"textarea","required":true,"placeholder":"・ゾーン追加\n・WAF ルール設定\n・動作確認"},{"id":"prerequisites","label":"前提条件・プラン","type":"text","required":false,"placeholder":"例: Pro プラン以上"},{"id":"troubleshooting","label":"トラブルシューティング","type":"textarea","required":false,"placeholder":"よくある問題と解決策"},{"id":"notes","label":"補足・特記事項","type":"textarea","required":false},{"id":"reference_urls","label":"参考 URL","type":"url_list","required":false}]}'
WHERE id = 't-app-01';

-- ─── t-zt-01: Zero Trust 導入ステップバイステップ ───
UPDATE templates SET input_fields_json = '{"fields":[{"id":"component","label":"ZT コンポーネント","type":"text","required":true,"placeholder":"例: Access, Gateway, Tunnel, CASB"},{"id":"services_used","label":"使用する Cloudflare サービス","type":"tag_select","required":true,"options":["Access","Gateway","Tunnel (cloudflared)","CASB","Browser Isolation","DLP","WARP Client","DEX","Email Security","Magic WAN (ZT 連携)"]},{"id":"challenge","label":"組織の課題・導入目的","type":"textarea","required":true,"placeholder":"従来のセキュリティ課題と ZT で解決したいこと"},{"id":"previous_solution","label":"Cloudflare 採用前の SSE / SASE ソリューション","type":"textarea","required":false,"placeholder":"例: Zscaler ZIA + Palo Alto Prisma Access を利用。課題は..."},{"id":"idp","label":"使用する IdP","type":"select","required":true,"options":["Okta","Azure AD (Entra ID)","Google Workspace","OneLogin","Ping Identity","その他"]},{"id":"target_audience","label":"対象読者","type":"tag_select","required":true,"options":["セキュリティエンジニア","IT 管理者","ネットワークエンジニア","CISO / セキュリティ責任者","SRE","情シス担当者"]},{"id":"target_audience_other","label":"対象読者（その他）","type":"text","required":false,"placeholder":"上記にない場合は自由記述"},{"id":"steps","label":"導入手順（箇条書き）","type":"textarea","required":true,"placeholder":"Phase ごとのざっくりした手順"},{"id":"before_after","label":"Before/After の違い","type":"textarea","required":false,"placeholder":"従来構成との比較ポイント"},{"id":"policy_example","label":"ポリシー例","type":"textarea","required":false},{"id":"results","label":"導入効果（数値）","type":"textarea","required":false,"placeholder":"定量的な改善指標"},{"id":"ops_tips","label":"運用のポイント","type":"textarea","required":false},{"id":"notes","label":"補足・特記事項","type":"textarea","required":false},{"id":"reference_urls","label":"参考 URL","type":"url_list","required":false}]}'
WHERE id = 't-zt-01';

-- ─── t-net-01: Network Services 構成ガイド ───
UPDATE templates SET input_fields_json = '{"fields":[{"id":"service_name","label":"対象サービス","type":"text","required":true,"placeholder":"例: Magic Transit, Magic WAN, Spectrum"},{"id":"services_used","label":"使用する Cloudflare サービス","type":"tag_select","required":true,"options":["Magic Transit","Magic WAN","Magic Firewall","Spectrum","Argo Smart Routing","Argo Tiered Cache","Load Balancing","Network Interconnect (CNI)","WARP Connector","Cloudflare Tunnel"]},{"id":"challenge","label":"ネットワーク課題","type":"textarea","required":true,"placeholder":"既存のネットワーク課題"},{"id":"previous_solution","label":"Cloudflare 採用前のネットワークソリューション","type":"textarea","required":false,"placeholder":"例: MPLS 回線 + Cisco SD-WAN を利用。課題は..."},{"id":"target_audience","label":"対象読者","type":"tag_select","required":true,"options":["ネットワークエンジニア","インフラエンジニア","SRE","セキュリティエンジニア","IT 管理者","データセンター運用者"]},{"id":"target_audience_other","label":"対象読者（その他）","type":"text","required":false,"placeholder":"上記にない場合は自由記述"},{"id":"architecture","label":"構成概要（箇条書き）","type":"textarea","required":true,"placeholder":"接続方式、ルーティング、冗長化など"},{"id":"steps","label":"設定手順（箇条書き）","type":"textarea","required":true,"placeholder":"オンボーディング〜本番切替までの流れ"},{"id":"performance","label":"パフォーマンス・可用性データ","type":"textarea","required":false,"placeholder":"レイテンシ改善、DDoS 防御実績等"},{"id":"notes","label":"補足・特記事項","type":"textarea","required":false},{"id":"reference_urls","label":"参考 URL","type":"url_list","required":false}]}'
WHERE id = 't-net-01';

-- ─── t-dev-03: Workers AI / AI Gateway 活用 ───
UPDATE templates SET input_fields_json = '{"fields":[{"id":"use_case","label":"AI ユースケース","type":"text","required":true,"placeholder":"例: 社内文書の要約、チャットボット"},{"id":"challenge","label":"解決したい課題","type":"textarea","required":true,"placeholder":"ビジネス課題の説明"},{"id":"models","label":"使用モデル（自由記述）","type":"textarea","required":true,"placeholder":"例:\n・テキスト生成: @cf/meta/llama-3.3-70b-instruct-fp8-fast\n・埋め込み: @cf/baai/bge-large-en-v1.5\n・画像生成: @cf/stabilityai/stable-diffusion-xl-base-1.0"},{"id":"integrations","label":"Workers や他システムとの連携","type":"textarea","required":false,"placeholder":"例: Workers から AI Gateway 経由で呼び出し、結果を D1 に保存。外部 API (OpenAI) へのフォールバックあり"},{"id":"target_audience","label":"対象読者","type":"tag_select","required":true,"options":["AI / ML エンジニア","バックエンドエンジニア","フルスタックエンジニア","プロダクトマネージャー","SRE","データサイエンティスト"]},{"id":"target_audience_other","label":"対象読者（その他）","type":"text","required":false,"placeholder":"上記にない場合は自由記述"},{"id":"steps","label":"実装手順（箇条書き）","type":"textarea","required":true,"placeholder":"プロンプト設計〜デプロイまでの流れ"},{"id":"use_rag","label":"RAG を使用するか","type":"select","required":false,"options":["はい (Vectorize 連携)","いいえ"]},{"id":"ai_gateway_config","label":"AI Gateway 設定","type":"textarea","required":false,"placeholder":"Rate Limiting, Caching, Logging の設定"},{"id":"prompt_example","label":"プロンプト例","type":"code","required":false,"placeholder":"実際に使ったプロンプト"},{"id":"evaluation","label":"評価指標・チューニング結果","type":"textarea","required":false,"placeholder":"精度、レイテンシ、コスト等"},{"id":"notes","label":"補足・特記事項","type":"textarea","required":false},{"id":"reference_urls","label":"参考 URL","type":"url_list","required":false}]}'
WHERE id = 't-dev-03';
